# Build extra small Deno release

name: xs-release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: oprypin/find-latest-tag@v1
        with:
          repository: denoland/deno
          releases-only: true
        id: deno
      - run: echo "Deno is at version ${{ steps.deno.outputs.tag }}"
      - uses: actions/checkout@v2
        with:
          repository: denoland/deno
          ref: ${{ steps.deno.outputs.tag }}
      - uses: actions/checkout@v2
        with:
          path: "deno-xs"
      - run: cp deno-xs/Cargo.toml Cargo.toml
      - run: cat Cargo.toml
      - name: Install latest Rust nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --locked
      - name: Zip release
        working-directory: target/release
        run: zip -r deno-x86_64-unknown-linux-gnu.zip deno
      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: release
          path: target/release/deno-x86_64-unknown-linux-gnu.zip
      - name: Download build
        uses: actions/download-artifact@v2
      - name: Release ${{ steps.deno.outputs.tag }}
        uses: ncipollo/release-action@v1
        with:
          tag: "${{ steps.deno.outputs.tag }}"
          name: "${{ steps.deno.outputs.tag }}"
          prerelease: ${{ steps.deno.outputs.tag == 'latest' }}
          allowUpdates: true
          replacesArtifacts: true
          artifacts: "release/*"
          body: "Unofficial Deno ${{ steps.deno.outputs.tag }} release, optimized for size"
          token: ${{ secrets.GITHUB_TOKEN }}
