# Build extra small Deno release

name: xs-release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: oprypin/find-latest-tag@v1
        with:
          repository: denoland/deno
          releases-only: true
        id: deno
      - run: echo "Deno is at version ${{ steps.deno.outputs.tag }}"
      - uses: actions/checkout@v2
        with:
          repository: denoland/deno
          ref: ${{ steps.deno.outputs.tag }}
      - name: Install latest Rust nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --locked
      - name: Zip release
        working-directory: target/release
        run: zip -r deno-x86_64-unknown-linux-gnu.zip deno
      - name: Upload release
        uses: actions/upload-artifact@v2
        with:
          name: release
          path: |
            target/release/deno-x86_64-unknown-linux-gnu.zip
